server:
  port: 8002

logging:
  pattern:
    #控制台日志输出格式
    console: "%d{yyyy-MM-dd HH:mm:ss} [%p] %logger{36}-> %m%n"
  level:
    root: INFO
    com:
      ufgov: DEBUG
    org:
      springframework:
        web: DEBUG
        jdbc.core:
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE

mybatis:
  # config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lxh.cdata.**.entities  # 所有Entity别名类所在包
  # mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
  configuration:
    mapUnderscoreToCamelCase: true # 驼峰命名

spring:
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/varDictDb?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
#    dbcp2:
#      min-idle: 5                                # 数据库连接池的最小维持连接数
#      initial-size: 5                            # 初始化连接数
#      max-total: 5                               # 最大连接数
#      max-wait-millis: 150                       # 等待连接获取的最大超时时间
